### ISSUE TITLE
关于软件的使用

### ISSUE THREAD

**Issue by sanfengzhanggif** [xyranger/ssr-download#1]
你好  这个APP 现在好了 需要一个国外AppleId登录 才可以使用?登录自己闪退

**Comment by xyranger** [comment]
请支持正版，此项目只是暂时提供给yahaha临时下载安装使用。不解答任何非正版下载安装问题，有问题到yahaha官方群咨询https://t.me/YahahaLTD

**Comment by xyranger** [comment]
请支持正版，此项目只是暂时提供给yahaha临时下载安装使用。不解答任何非正版下载安装问题，有问题到yahaha官方群咨询https://t.me/YahahaLTD
